kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: demo-service-supplier
  name: demo-service-supplier 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-supplier
  template:
    metadata:
      name: demo-service-supplier
      labels:
        app: demo-service-supplier
    spec:
      containers:
      - name: demo-service-supplier
        image: repository:5000/demo-service-supplier
        imagePullPolicy: Always
        env:
          - name: GIT_URL
            value: "http://demo-service-config:9000"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service-supplier
  name: demo-service-supplier
  namespace: default
spec:
  ports:
  - port: 9004 
    targetPort: 9004
  selector:
    app: demo-service-supplier
