kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: demo-service-supplier
  name: demo-service-supplier 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-supplier
  template:
    metadata:
      name: demo-service-supplier
      labels:
        app: demo-service-supplier
    spec:
      containers:
      - name: demo-service-supplier
        image: 192.168.0.209:5000/demo-service-supplier
        imagePullPolicy: Always
        env:
          - name: REGISTRY_URL
            value: "http://192.168.0.209:31001/eureka"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service-supplier
  name: demo-service-supplier
  namespace: default
spec:
  ports:
  - port: 9004 
    targetPort: 9004
  selector:
    app: demo-service-supplier
